/* UNIT.FURNITURE: тексты RU/EN.
   Источник фактов: Figma «Каталог» 2026 (refs/catalog-2026-10/catalog-db.json).
   Цифр, которых нет в каталоге (сроки, гарантия, цены), не писать.
   <i class="u5">UNIT.</i> — связка бренда: UNIT. 500, хвост 400. Тире в копирайте не ставим. */
window.DICT = {
  ru: {
    'pp.ask': 'Получить расчёт',
    'pp.sol.lead': 'Модель можно взять отдельно или в составе комплекта под пространство',
    'pp.sol': 'Подойдёт для решений',
    'pp.priceV': 'по запросу',
    'pp.priceK': 'Стоимость',
    'usex.restaurant': 'ресторан',
    'usex.hotel': 'отель',
    'usex.villa': 'вилла',
    'usex.home': 'дом',
    'room.terrace': 'терраса и бассейн',
    'room.dining': 'столовая',
    'room.living': 'гостиная',
    'room.bedroom': 'спальня',
    'pp.use': 'Назначение',
    'sort.line': 'По линейке',
    'sort.name': 'По названию',
    'sort.def': 'Как в коллекции',
    'cat.sort': 'Сортировка',
    'use.restaurant': 'Ресторан',
    'use.hotel': 'Отель',
    'use.villa': 'Вилла',
    'use.home': 'Дом',
    'cat.useAll': 'Любой объект',
    'cat.use': 'Объект',
    'fm.metal': 'Металл',
    'fm.ply': 'Фанера',
    'fm.teak': 'Тик',
    'cat.matAll': 'Любой материал',
    'cat.mat': 'Материал',
    'lead.n2': 'Можно отправить фото, план, референсы или выбранные модели.',
    'lead.n1': 'Стоимость рассчитываем индивидуально.',
    'clim.lead': 'Учитываем климат Бали, открытые зоны и регулярное использование в жилых и коммерческих пространствах',
    'sol.cta': 'Подобрать решение под мой объект',
    'sol.lead': 'Собираем мебель под конкретное пространство, от спальни до комплектации всей виллы',
    'sol.h2': 'Готовые интерьерные решения',
    'what.go.key': 'Обсудить комплектацию',
    'what.go': 'Смотреть модели',
    'what.key.t': 'Комплектация виллы, дома, отеля или ресторана в едином стиле.',
    'what.key': 'Объект под ключ',
    'what.com.t': 'Решения для отелей, ресторанов, лобби, ресепшн и лаунж-зон.',
    'what.com': 'Коммерческие объекты',
    'what.out.t': 'Шезлонги, уличные диваны и подушки для террас, бассейнов и садов.',
    'what.out': 'Терраса и бассейн',
    'what.home.t': 'Кровати, диваны, кресла, стулья и мягкие элементы для жилых пространств.',
    'what.home': 'Мебель для дома',
    'what.lead': 'Выберите готовую модель из каталога или доверьте нам подбор мебели под весь объект: спальню, гостиную, террасу, ресторан, отель или виллу целиком',
    'what.h2': 'От отдельных предметов до комплектации пространства',
    'meta.title': 'UNIT.FURNITURE: авторская мебель собственного производства на Бали',
    'skip': 'К содержанию',
    'nav.collections': 'Коллекции', 'nav.catalog': 'Каталог', 'nav.production': 'Производство',
    'nav.custom': 'Кастомизация', 'nav.how': 'Как заказать', 'nav.faq': 'Вопросы',
    'nav.designers': 'Для дизайнеров', 'crumb.home': 'Главная',
    'dz.h2': 'Для дизайнеров и архитекторов',
    'dz.lead': 'Станем производственным партнёром на Бали для ваших вилл, отелей и коммерческих проектов',
    'dz.text': 'Используйте модели <i class="u5">UNIT.</i>FURNITURE в своих проектах и адаптируйте их под интерьер или отдайте нам в производство мебель по вашим чертежам, референсам и спецификациям.',
    'dz.c1': 'Работа по референсам и чертежам', 'dz.c2': 'Адаптация размеров', 'dz.c3': 'Подбор тканей и материалов',
    'dz.c4': 'Производство на Бали', 'dz.c5': 'Комплектация объекта', 'dz.c6': 'Индивидуальный расчёт',
    'dz.join': 'Стать партнёром', 'dz.discuss': 'Обсудить проект', 'dz.more': 'Подробнее для дизайнеров',
    'dzp.title': 'Для дизайнеров и архитекторов',
    'dzp.h1': 'Производственный партнёр для дизайнеров и архитекторов на Бали',
    'dzp.lead': 'Делаем мебель по моделям каталога, референсам, чертежам и задачам конкретного проекта',
    'dzp.can': 'Что мы можем', 'dzp.can.lead': 'Берём на себя производство, а интерьер остаётся вашим',
    'dzp.c1': 'Адаптировать модели', 'dzp.c1.t': 'Меняем размеры, посадку, ткань и отделку моделей каталога под ваш интерьер.',
    'dzp.c2': 'Производить по референсам', 'dzp.c2.t': 'Делаем мебель по вашим чертежам, эскизам и референсам.',
    'dzp.c3': 'Подбирать материалы', 'dzp.c3.t': 'Подбираем дерево, ткани и наполнители для помещений и улицы.',
    'dzp.c4': 'Комплектовать объект', 'dzp.c4.t': 'Собираем мебель для виллы, дома, отеля или ресторана в едином стиле.',
    'dzp.c5': 'Работать с коммерцией', 'dzp.c5.t': 'Отели, рестораны, лобби, ресепшн и лаунж-зоны.',
    'dzp.c6': 'Считать под проект', 'dzp.c6.t': 'Готовим расчёт по моделям, материалам и объёму заказа.',
    'dzp.how': 'Как проходит работа', 'dzp.how.lead': 'От брифа до мебели на объекте',
    'dzp.s1': 'Бриф', 'dzp.s1.t': 'Получаем задачу, чертежи, референсы или список моделей.',
    'dzp.s2': 'Подбор', 'dzp.s2.t': 'Предлагаем модели, материалы и варианты доработки.',
    'dzp.s3': 'Согласование', 'dzp.s3.t': 'Утверждаем с вами размеры, ткани и отделку.',
    'dzp.s4': 'Расчёт', 'dzp.s4.t': 'Считаем стоимость и называем срок.',
    'dzp.s5': 'Производство', 'dzp.s5.t': 'Изготавливаем мебель на своём производстве на Бали.',
    'dzp.s6': 'Доставка', 'dzp.s6.t': 'Доставляем и собираем мебель на объекте.',
    'dzp.cta.h': 'Обсудим ваш проект', 'dzp.cta.lead': 'Пришлите чертежи, референсы или список моделей. Ответим и пришлём расчёт',
    'dzp.mgr': 'Связаться с менеджером напрямую',
    'nav.solutions': 'Решения', 'nav.projects': 'Проекты', 'nav.contacts': 'Контакты', 'nav.materials': 'Материалы',
    'hdr.cta': 'Получить расчёт', 'cta.quote': 'Получить расчёт', 'cart.back': 'К моделям', 'cart.closeBtn': 'Закрыть', 'cart.sum': 'Моделей: {n}, штук: {q}', 'cart.sum0': 'Модели не выбраны, опишите задачу в комментарии.', 'col.remove': 'Убрать линейку', 'hdr.menu': 'Меню', 'hdr.close': 'Закрыть меню', 'hdr.cart': 'Корзина',

    'hero.chip': 'Собственное производство', 'hero.tag2': 'Кастомизация', 'hero.tag3': 'Для дома, улицы и бизнеса',
    'hero.h1': 'Хай-тек мебель собственного производства и интерьеры на Бали',
    'hero.lead': 'Мебель для вилл, домов, отелей, ресторанов и террас. От одной модели до объекта под ключ',
    'hero.cta1': 'Смотреть каталог', 'hero.cta2': 'Обставить объект',
    'hero.cap': 'Sofa Outdoor Type 4, коллекция 2026',
    'path.h2': 'Мебель для дома и для объекта',
    'path.home': 'Для дома', 'path.home.t': 'Вилла, дом или апартаменты. Выберите модели в каталоге, укажите количество, и мы пришлём расчёт.', 'path.home.go': 'Выбрать модели',
    'path.pro': 'Для объекта', 'path.pro.t': 'Дизайнерам, архитекторам, застройщикам, отелям и ресторанам. Адаптируем модели и комплектуем объект целиком.', 'path.pro.go': 'Адаптировать под объект',

    'col.h2': 'Три линейки одной коллекции',
    'col.lead': 'Awan, Axis и Reason собраны в общем стиле: модели одной линейки легко комплектовать в один интерьер',
    'col.models': 'Модели', 'col.cats': 'Категории', 'col.frame': 'Материалы каркаса', 'col.count': 'Моделей в линейке',
    'col.go': 'Смотреть линейку', 'col.addall': 'Добавить линейку в корзину', 'col.added': 'Линейка в корзине',

    'cats.h2': 'Каталог мебели',
    'cats.lead': 'Выберите категорию или отправьте нам запрос: поможем подобрать решение под ваш объект',
    'cats.all': 'Весь каталог',

    'band.h': 'Собственное производство на Бали',
    'band.p': 'От выбора материалов до финальной сборки',

    'prod.h2': 'Делаем сами и проверяем на своих объектах',
    'prod.lead': '<i class="u5">UNIT.</i>FURNITURE входит в группу <i class="u5">UNIT.</i>, которая строит виллы и управляет ими на Бали',
    'prod.r1': 'Производство', 'prod.t1': 'Собственное производство на Бали позволяет контролировать каждый этап создания мебели: от выбора материалов до финальной сборки. Современное оборудование и контроль на каждом этапе дают точность исполнения.',
    'prod.r2': 'Дизайн', 'prod.t2': 'Хороший дизайн остаётся актуальным вне времени. Мы делаем мебель, в которой эстетика сочетается с комфортом, функциональностью и долговечностью.',
    'prod.r3': 'Проекты <i class="u5">UNIT.</i>', 'prod.t3': 'Мебель <i class="u5">UNIT.</i>FURNITURE стоит в собственных проектах <i class="u5">UNIT.</i>, поэтому мы уверены в её качестве, комфорте и долговечности.',

    'mat.h2': 'Материалы, рассчитанные на жизнь на Бали',
    'mat.lead': 'Мебель <i class="u5">UNIT.</i>FURNITURE создаётся с учётом влажности, солнца, активного использования и тропического климата',
    'mat.wood': 'Дерево', 'mat.wood.t': 'Натуральная древесина, подобранная под особенности каждой модели.',
    'mat.fabric': 'Ткани', 'mat.fabric.t': 'Разные фактуры, оттенки и уровни износостойкости для жилых и коммерческих пространств.',
    'mat.filling': 'Наполнители', 'mat.filling.t': 'Современные наполнители, которые сохраняют комфорт, форму и внешний вид мебели.',
    'mat.hardware': 'Фурнитура', 'mat.hardware.t': 'Надёжная и долговечная фурнитура и конструктивные решения для стабильной эксплуатации.',
    'clim.h3': 'Влажность и эксплуатация',
    'clim.1': 'Влажный климат', 'clim.1.t': 'Подбираем материалы, отделки и конструкции с учётом влажности и перепадов температуры.',
    'clim.2': 'Солнце и улица', 'clim.2.t': 'Для открытых зон берём решения, рассчитанные на террасы, бассейны, сады и ежедневную эксплуатацию.',
    'clim.3': 'Регулярное использование', 'clim.3.t': 'Мебель сохраняет комфорт, внешний вид и устойчивость в домах, виллах, отелях и ресторанах.',
    'clim.tag1': 'Для дома', 'clim.tag2': 'Для улицы и бассейна', 'clim.tag3': 'Для коммерческих объектов',

    'cus.h2': 'Кастомизация под ваш объект',
    'cus.lead': 'Размеры, ткани, цвета и комплектация адаптируются под задачу пространства',
    'cus.r1': 'Размеры', 'cus.t1': 'Адаптируем длину, ширину, высоту, посадку и конфигурацию.',
    'cus.r2': 'Ткани', 'cus.t2': 'Подбираем фактуры для помещений и улицы.',
    'cus.r3': 'Цвета', 'cus.t3': 'Выбираем оттенки дерева, обивки и акцентов.',
    'cus.r4': 'Комплектация', 'cus.t4': 'Собираем решение от отдельной модели до полного комплекта.',
    'cus.cta': 'Обсудить кастомизацию',
    'sol.h3': 'Готовые решения для дизайнеров, архитекторов и застройщиков',
    'sol.bedroom': 'Спальня', 'sol.bedroom.t': 'Кровати, тумбы, кресла, пуфы, подушки',
    'sol.living': 'Гостиная', 'sol.living.t': 'Диваны, кресла, пуфы и подушки',
    'sol.outdoor': 'Терраса и бассейн', 'sol.outdoor.t': 'Уличные диваны, шезлонги и подушки',
    'sol.turnkey': 'Объект под ключ', 'sol.turnkey.t': 'Вилла, дом, отель или ресторан в едином стиле',
    'sol.go': 'Смотреть модели', 'sol.go.turnkey': 'Обсудить комплектацию',

    'proj.h2': 'Мебель в реальных проектах',
    'proj.lead': 'Наша мебель стоит в жилых и коммерческих пространствах <i class="u5">UNIT.</i>: UNIT Space City и Black Sands Oasis. Откройте фото, чтобы увидеть модели в кадре',
    'proj.more': 'Показать все фото', 'proj.less': 'Свернуть фото',
    'proj.inshot': 'В этом кадре', 'proj.addshot': 'Добавить в корзину', 'proj.addshot2': 'Добавить модели в корзину', 'proj.inreq': 'Модели в корзине, открыть',
    'proj.open': 'Открыть фото', 'proj.close': 'Закрыть', 'proj.prev': 'Предыдущее фото', 'proj.next': 'Следующее фото',

    'how.h2': 'Как заказать',
    'how.lead': 'От первого запроса до готовой мебели на объекте',
    'how.s1': 'Консультация', 'how.s1.t': 'Получаем ваш запрос с выбранными моделями, планом объекта или референсами.',
    'how.s2': 'Подбор', 'how.s2.t': 'Подбираем мебель, материалы и решения под ваш проект.',
    'how.s3': 'Расчёт', 'how.s3.t': 'Считаем стоимость заказа и называем срок.',
    'how.s4': 'Производство', 'how.s4.t': 'После согласования запускаем заказ в производство на Бали.',
    'how.s5': 'Доставка', 'how.s5.t': 'Организуем доставку и, если нужно, установку на объекте.',
    'how.cta': 'Оставить заявку',

    'faq.h2': 'Частые вопросы',
    'faq.lead': 'Коротко о том, что спрашивают перед заказом',
    'faq.q1': 'Почему на сайте нет цен?', 'faq.a1': 'Стоимость зависит от модели, размеров, ткани и количества. Добавьте модели в корзину с количеством, и мы пришлём расчёт под ваш объект.',
    'faq.q2': 'Какие сроки изготовления?', 'faq.a2': 'Срок называем вместе с расчётом: он зависит от моделей, количества и доработок. Если у объекта есть дата открытия или заселения, укажите её в заявке.',
    'faq.q3': 'Можно изменить размер, цвет или ткань?', 'faq.a3': 'Да. Адаптируем размеры и эргономику, подбираем оттенки дерева, тканей и отделки для помещений и улицы.',
    'faq.q4': 'Выдержит ли мебель климат Бали и улицу?', 'faq.a4': 'Мебель разрабатываем под тропический климат: материалы и конструкции рассчитаны на высокую влажность и перепады температуры, для улицы берём материалы, устойчивые к солнцу.',
    'faq.q5': 'Что прислать для расчёта?', 'faq.a5': 'Выбранные модели и количество, план объекта или референсы. Подойдёт и короткое описание задачи: подберём модели сами.',
    'faq.q6': 'Доставляете и собираете на объекте?', 'faq.a6': 'Да, организуем доставку и монтаж на объекте. Это последний шаг заказа после производства.',
    'faq.q7': 'Работаете с дизайнерами и застройщиками?', 'faq.a7': 'Да. Предлагаем готовые решения для дизайнеров, архитекторов и застройщиков и сопровождаем проект от разработки до реализации.',

    'lead.h2': 'Создадим мебель для вашего проекта',
    'lead.lead': 'Напишите удобным способом: подберём решение, рассчитаем стоимость и подготовим предложение',
    'lead.email': 'Почта', 'lead.ig': 'Instagram', 'lead.group': 'Группа компаний', 'lead.group.v': '<i class="u5">UNIT.</i>DEVELOPER, Бали',
    'f.name': 'Имя', 'f.contact': 'Телефон, WhatsApp или email', 'f.contact.hint': 'Например, +62 812 000 00 00 или name@mail.com',
    'f.type': 'Объект', 'f.type.ph': 'Выберите тип объекта',
    'f.type.villa': 'Вилла', 'f.type.house': 'Дом', 'f.type.apart': 'Апартаменты', 'f.type.hotel': 'Отель', 'f.type.rest': 'Ресторан или кафе', 'f.type.other': 'Другое',
    'f.type.garden': 'Терраса или сад', 'f.type.design': 'Дизайнерский проект',
    'f.need': 'Что подобрать', 'f.need.lobby': 'Ресепшн и лобби', 'f.need.rest': 'Ресторан или бар',
    'f.files': 'Фото, план или референсы', 'f.files.btn': 'Прикрепить файлы', 'f.files.hint': 'JPG, PNG, PDF или DWG, до 10 файлов по 20 МБ',
    'f.files.rm': 'Убрать файл {name}', 'f.err.files': 'Не добавили: {list}. Нужны файлы до 20 МБ, всего не больше 10.',
    'ok.files': 'Файлов: {n}',
    'f.models': 'Модели из корзины', 'f.models.empty': 'Пока пусто. Добавьте модели из <a href="catalog.html">каталога</a> или опишите задачу ниже.',
    'f.models.edit': 'Изменить количество',
    'f.msg': 'Комментарий', 'f.msg.ph': 'Что нужно, сколько, к какой дате',
    'f.opt': 'необязательно',
    'f.agree': 'Согласен на <a href="consent.html">обработку персональных данных</a>',
    'f.submit': 'Отправить заявку', 'f.sending': 'Отправляем…',
    'f.note': 'Цен на сайте нет: стоимость считаем под модели, количество и ткань.',
    'f.err.title': 'Проверьте форму:',
    'f.err.name': 'Укажите имя, чтобы мы знали, как к вам обращаться.',
    'f.err.contact': 'Укажите телефон, WhatsApp или email: минимум 6 цифр или адрес с @.',
    'f.err.agree': 'Отметьте согласие на обработку данных, без него мы не можем ответить.',
    'ok.h': 'Заявка принята',
    'ok.p': 'Свяжемся с вами по контакту {c}, уточним детали и пришлём расчёт.',
    'ok.list': 'В заявке:', 'ok.none': 'Модели не выбраны, ориентируемся на комментарий.',
    'ok.more': 'Смотреть каталог', 'ok.new': 'Новая заявка',

    'cart.h': 'Корзина', 'cart.empty': 'В корзине пока пусто. Добавьте модели из каталога, количество можно изменить здесь.',
    'cart.go': 'Перейти к отправке', 'cart.browse': 'Открыть каталог',
    'cart.note': 'Цен на сайте нет. Пришлём расчёт под модели и количество.',
    'cart.remove': 'Убрать', 'cart.total': 'Моделей: {n}, штук: {q}',
    'qty.minus': 'Меньше', 'qty.plus': 'Больше', 'qty': 'Количество',
    'add': 'В корзину', 'add.more': 'Добавить в корзину', 'added': 'В корзине',
    'toast.added': '{name} в корзине', 'toast.open': 'Открыть корзину',

    'cat.h1': 'Каталог',
    'cat.lead': 'Выберите модель или отправьте нам запрос: поможем подобрать мебель под ваш объект',
    'cat.all': 'Все', 'cat.filter': 'Категория', 'cat.line': 'Линейка', 'cat.lineAll': 'Все линейки',
    'cat.shown': 'Моделей: {n}',
    'cat.empty.h': 'Под эти фильтры готовых моделей нет',
    'cat.empty.p': 'Сделаем под заказ: опишите задачу в заявке.',
    'cat.empty.reset': 'Сбросить фильтры', 'cat.empty.lead': 'Описать задачу',
    'cat.noDims': 'Размеры по запросу',
    'cat.env': 'Где стоит', 'env.indoor': 'Для помещений', 'env.outdoor': 'Для улицы',
    'tag.fabric': 'Ткань на выбор', 'tag.size': 'Размер под заказ', 'card.price': 'Стоимость по запросу',

    'pp.crumb': 'Каталог', 'pp.line': 'Линейка', 'pp.cat': 'Категория', 'pp.dims': 'Размеры, В × Ш × Г',
    'pp.price': 'Стоимость по запросу: считаем под количество, ткань и размер.',
    'pp.custom': 'Изменить размер или ткань', 'pp.more': 'Ещё из линейки {c}', 'pp.similar': 'Похожие модели',
    'pp.photo': 'Фото {n} из {m}', 'pp.lineall': 'Вся линейка {c} в каталоге: {n}',
    'pp.custom.h': 'Что можно изменить',

    'cat.beds': 'Кровати', 'cat.sofas': 'Диваны', 'cat.chairs': 'Стулья', 'cat.armchairs': 'Кресла и пуфы',
    'cat.nightstands': 'Тумбы', 'cat.outdoor': 'Уличные диваны', 'cat.sunbeds': 'Шезлонги', 'cat.textile': 'Подушки',
    'n.models': '{n} модел{e}',
    'd.chairs': 'Стул на тиковом каркасе для столовой, кухни или бара. Ткань и размеры адаптируем под объект.',
    'd.beds': 'Кровать с каркасом из фанеры 18 мм. Размер, изголовье и обивку адаптируем под спальню виллы, дома или отельного номера.',
    'd.armchairs': 'Кресло или пуф для гостиной и спальни. Ткань, цвет и размеры подбираем под интерьер.',
    'd.sofas': 'Диван для гостиной, ресепшн или лаунж-зоны. Ткань, размер и конфигурацию подбираем под пространство.',
    'd.nightstands': 'Прикроватная тумба-куб. Отделку подбираем под спальню.',
    'd.outdoor': 'Уличный диван на тиковом каркасе для террасы и зоны у бассейна. Материалы рассчитаны на солнце и влажность.',
    'd.sunbeds': 'Шезлонг на тиковом каркасе для террасы и бассейна. Материалы рассчитаны на солнце и влажность.',
    'd.textile': 'Декоративные подушки к диванам коллекции, в двух вариантах цвета.',

    'ft.about': 'Авторская мебель собственного производства на Бали для частных и коммерческих объектов.',
    'ft.nav': 'Разделы', 'ft.contacts': 'Контакты', 'ft.legal': 'Правовая информация', 'ft.consent': 'Согласие на обработку данных',
    'ft.part': 'Часть группы <a href="https://unitdeveloper.com/" target="_blank" rel="noopener"><i class="u5">UNIT.</i>DEVELOPER</a>',
    'ft.top': 'Наверх',
    'pdf.dl': 'Скачать каталог PDF', 'pdf.ft': 'Каталог 2026 (PDF)', 'pdf.href': 'assets/UNIT-FURNITURE-catalog-2026-RU.pdf'
  },
  en: {
    'pp.ask': 'Get a quote',
    'pp.sol.lead': 'Take the model on its own or as part of a set for the space',
    'pp.sol': 'Fits these solutions',
    'pp.priceV': 'on request',
    'pp.priceK': 'Price',
    'usex.restaurant': 'restaurant',
    'usex.hotel': 'hotel',
    'usex.villa': 'villa',
    'usex.home': 'home',
    'room.terrace': 'terrace and pool',
    'room.dining': 'dining room',
    'room.living': 'living room',
    'room.bedroom': 'bedroom',
    'pp.use': 'Use',
    'sort.line': 'By line',
    'sort.name': 'By name',
    'sort.def': 'As in the collection',
    'cat.sort': 'Sort',
    'use.restaurant': 'Restaurant',
    'use.hotel': 'Hotel',
    'use.villa': 'Villa',
    'use.home': 'Home',
    'cat.useAll': 'Any property',
    'cat.use': 'Property',
    'fm.metal': 'Metal',
    'fm.ply': 'Plywood',
    'fm.teak': 'Teak',
    'cat.matAll': 'Any material',
    'cat.mat': 'Material',
    'lead.n2': 'You can send photos, a floor plan, references or selected models.',
    'lead.n1': 'The price is calculated individually.',
    'clim.lead': 'We account for the Bali climate, outdoor areas and regular use in homes and hospitality spaces',
    'sol.cta': 'Find a solution for my property',
    'sol.lead': 'We furnish a specific space, from a bedroom to an entire villa',
    'sol.h2': 'Ready interior solutions',
    'what.go.key': 'Discuss furnishing',
    'what.go': 'View models',
    'what.key.t': 'Furnishing a villa, home, hotel or restaurant in one style.',
    'what.key': 'Turnkey property',
    'what.com.t': 'Solutions for hotels, restaurants, lobbies, receptions and lounge areas.',
    'what.com': 'Hospitality projects',
    'what.out.t': 'Sun loungers, outdoor sofas and pillows for terraces, pools and gardens.',
    'what.out': 'Terrace and pool',
    'what.home.t': 'Beds, sofas, armchairs, chairs and soft pieces for living spaces.',
    'what.home': 'Furniture for the home',
    'what.lead': 'Choose a ready model from the catalog or let us furnish the whole property: a bedroom, living room, terrace, restaurant, hotel or an entire villa',
    'what.h2': 'From single pieces to a fully furnished space',
    'meta.title': 'UNIT.FURNITURE: designer furniture made in our own workshop in Bali',
    'skip': 'Skip to content',
    'nav.collections': 'Collections', 'nav.catalog': 'Catalog', 'nav.production': 'Production',
    'nav.custom': 'Customisation', 'nav.how': 'How to order', 'nav.faq': 'FAQ',
    'nav.designers': 'For designers', 'crumb.home': 'Home',
    'dz.h2': 'For designers and architects',
    'dz.lead': 'Your production partner in Bali for villas, hotels and commercial projects',
    'dz.text': 'Use <i class="u5">UNIT.</i>FURNITURE models in your projects and adapt them to the interior, or have us produce furniture to your drawings, references and specifications.',
    'dz.c1': 'Work from references and drawings', 'dz.c2': 'Adapted dimensions', 'dz.c3': 'Fabrics and materials selection',
    'dz.c4': 'Production in Bali', 'dz.c5': 'Furnishing the whole property', 'dz.c6': 'Project-based quote',
    'dz.join': 'Become a partner', 'dz.discuss': 'Discuss a project', 'dz.more': 'More for designers',
    'dzp.title': 'For designers and architects',
    'dzp.h1': 'Production partner for designers and architects in Bali',
    'dzp.lead': 'We make furniture from catalog models, references, drawings and the brief of a specific project',
    'dzp.can': 'What we do', 'dzp.can.lead': 'We take care of production, the interior stays yours',
    'dzp.c1': 'Adapt models', 'dzp.c1.t': 'We change the size, seat, fabric and finish of catalog models to suit your interior.',
    'dzp.c2': 'Produce from references', 'dzp.c2.t': 'We make furniture to your drawings, sketches and references.',
    'dzp.c3': 'Select materials', 'dzp.c3.t': 'We select wood, fabrics and fillings for indoor and outdoor spaces.',
    'dzp.c4': 'Furnish the property', 'dzp.c4.t': 'We furnish a villa, house, hotel or restaurant in one style.',
    'dzp.c5': 'Work with hospitality', 'dzp.c5.t': 'Hotels, restaurants, lobbies, receptions and lounge areas.',
    'dzp.c6': 'Quote per project', 'dzp.c6.t': 'We prepare a quote by models, materials and order volume.',
    'dzp.how': 'How we work', 'dzp.how.lead': 'From the brief to furniture on site',
    'dzp.s1': 'Brief', 'dzp.s1.t': 'We receive the task, drawings, references or a list of models.',
    'dzp.s2': 'Selection', 'dzp.s2.t': 'We suggest models, materials and possible changes.',
    'dzp.s3': 'Approval', 'dzp.s3.t': 'We agree on dimensions, fabrics and finishes with you.',
    'dzp.s4': 'Quote', 'dzp.s4.t': 'We calculate the cost and give the lead time.',
    'dzp.s5': 'Production', 'dzp.s5.t': 'We make the furniture in our own workshop in Bali.',
    'dzp.s6': 'Delivery', 'dzp.s6.t': 'We deliver and assemble the furniture on site.',
    'dzp.cta.h': 'Let’s discuss your project', 'dzp.cta.lead': 'Send drawings, references or a list of models. We will reply with a quote',
    'dzp.mgr': 'Contact a manager directly',
    'nav.solutions': 'Solutions', 'nav.projects': 'Projects', 'nav.contacts': 'Contacts', 'nav.materials': 'Materials',
    'hdr.cta': 'Get a quote', 'cta.quote': 'Get a quote', 'cart.back': 'Back to models', 'cart.closeBtn': 'Close', 'cart.sum': 'Models: {n}, pieces: {q}', 'cart.sum0': 'No models chosen, describe the task in the comment.', 'col.remove': 'Remove the line', 'hdr.menu': 'Menu', 'hdr.close': 'Close menu', 'hdr.cart': 'Cart',

    'hero.chip': 'Our own workshop', 'hero.tag2': 'Customisation', 'hero.tag3': 'Indoor, outdoor, commercial',
    'hero.h1': 'Hi-tech furniture production and interiors in Bali',
    'hero.lead': 'Furniture for villas, homes, hotels, restaurants and terraces. From a single model to a turnkey property',
    'hero.cta1': 'Browse the catalog', 'hero.cta2': 'Furnish a property',
    'hero.cap': 'Sofa Outdoor Type 4, 2026 collection',
    'path.h2': 'Furniture for a home and for a property',
    'path.home': 'For a home', 'path.home.t': 'A villa, house or apartment. Choose models in the catalog, set quantities and we will send a quote.', 'path.home.go': 'Choose models',
    'path.pro': 'For a property', 'path.pro.t': 'For designers, architects, developers, hotels and restaurants. We adapt models and furnish the whole property.', 'path.pro.go': 'Adapt to your property',

    'col.h2': 'Three lines, one collection',
    'col.lead': 'Awan, Axis and Reason share one style, so models from a line furnish a single interior with ease',
    'col.models': 'Models', 'col.cats': 'Categories', 'col.frame': 'Frame materials', 'col.count': 'Models in the line',
    'col.go': 'View the line', 'col.addall': 'Add the line to the cart', 'col.added': 'Line is in the cart',

    'cats.h2': 'Furniture catalog',
    'cats.lead': 'Choose a category or send us a request: we will help you find the right solution for your property',
    'cats.all': 'Full catalog',

    'band.h': 'Our own workshop in Bali',
    'band.p': 'From material selection to final assembly',

    'prod.h2': 'We make it ourselves and test it in our own properties',
    'prod.lead': '<i class="u5">UNIT.</i>FURNITURE is part of the <i class="u5">UNIT.</i> group, which builds and manages villas in Bali',
    'prod.r1': 'Production', 'prod.t1': 'In-house production in Bali lets us control every stage, from material selection to final assembly. Modern equipment and checks at every step keep the execution precise.',
    'prod.r2': 'Design', 'prod.t2': 'Good design stays relevant beyond trends. We make furniture where aesthetics meet comfort, function and durability.',
    'prod.r3': '<i class="u5">UNIT.</i> projects', 'prod.t3': '<i class="u5">UNIT.</i>FURNITURE is used in <i class="u5">UNIT.</i>’s own projects, which is why we are confident in its quality, comfort and durability.',

    'mat.h2': 'Materials made for life in Bali',
    'mat.lead': '<i class="u5">UNIT.</i>FURNITURE pieces are made for humidity, sun, active use and the tropical climate',
    'mat.wood': 'Wood', 'mat.wood.t': 'Natural wood selected for the features of each model.',
    'mat.fabric': 'Fabrics', 'mat.fabric.t': 'Textures, shades and wear resistance for residential and commercial spaces.',
    'mat.filling': 'Fillings', 'mat.filling.t': 'Modern fillings that keep the comfort, shape and look of the furniture.',
    'mat.hardware': 'Hardware', 'mat.hardware.t': 'Reliable, durable hardware and structural solutions for stable everyday use.',
    'clim.h3': 'Humidity and everyday use',
    'clim.1': 'Humid climate', 'clim.1.t': 'We choose materials, finishes and structures for humidity and temperature changes.',
    'clim.2': 'Sun and outdoors', 'clim.2.t': 'For open areas we use solutions made for terraces, pools, gardens and daily use.',
    'clim.3': 'Regular use', 'clim.3.t': 'The furniture keeps its comfort, look and stability in homes, villas, hotels and restaurants.',
    'clim.tag1': 'For homes', 'clim.tag2': 'For outdoor and pool areas', 'clim.tag3': 'For hospitality projects',

    'cus.h2': 'Customised for your property',
    'cus.lead': 'Dimensions, fabrics, colours and set composition are adapted to the space',
    'cus.r1': 'Dimensions', 'cus.t1': 'We adapt length, width, height, seat and configuration.',
    'cus.r2': 'Fabrics', 'cus.t2': 'We select textures for indoor and outdoor spaces.',
    'cus.r3': 'Colours', 'cus.t3': 'We choose shades of wood, upholstery and accents.',
    'cus.r4': 'Set composition', 'cus.t4': 'From a single model to a complete set.',
    'cus.cta': 'Discuss customisation',
    'sol.h3': 'Ready solutions for designers, architects and developers',
    'sol.bedroom': 'Bedroom', 'sol.bedroom.t': 'Beds, nightstands, armchairs, poufs, pillows',
    'sol.living': 'Living room', 'sol.living.t': 'Sofas, armchairs, poufs and pillows',
    'sol.outdoor': 'Terrace and pool', 'sol.outdoor.t': 'Outdoor sofas, sun loungers and pillows',
    'sol.turnkey': 'Turnkey property', 'sol.turnkey.t': 'A villa, house, hotel or restaurant in one style',
    'sol.go': 'View models', 'sol.go.turnkey': 'Discuss furnishing',

    'proj.h2': 'Furniture in real projects',
    'proj.lead': 'Our furniture is used in <i class="u5">UNIT.</i> residential and hospitality spaces: UNIT Space City and Black Sands Oasis. Open a photo to see the models in the shot',
    'proj.more': 'Show all photos', 'proj.less': 'Hide photos',
    'proj.inshot': 'In this shot', 'proj.addshot': 'Add to cart', 'proj.addshot2': 'Add these to cart', 'proj.inreq': 'In the cart, open it',
    'proj.open': 'Open photo', 'proj.close': 'Close', 'proj.prev': 'Previous photo', 'proj.next': 'Next photo',

    'how.h2': 'How to order',
    'how.lead': 'From the first request to finished furniture on site',
    'how.s1': 'Consultation', 'how.s1.t': 'We receive your request with chosen models, a floor plan or references.',
    'how.s2': 'Selection', 'how.s2.t': 'We select furniture, materials and solutions for your project.',
    'how.s3': 'Quote', 'how.s3.t': 'We calculate the cost of the order and give the lead time.',
    'how.s4': 'Production', 'how.s4.t': 'Once approved, the order goes into production in Bali.',
    'how.s5': 'Delivery', 'how.s5.t': 'We organise delivery and, if needed, installation on site.',
    'how.cta': 'Send a request',

    'faq.h2': 'Frequently asked questions',
    'faq.lead': 'Short answers to what people ask before ordering',
    'faq.q1': 'Why are there no prices on the site?', 'faq.a1': 'The cost depends on the model, size, fabric and quantity. Add models to the cart with quantities and we will send a quote for your property.',
    'faq.q2': 'How long does production take?', 'faq.a2': 'We give the lead time together with the quote: it depends on the models, quantity and changes. If your property has an opening or move-in date, put it in the request.',
    'faq.q3': 'Can I change the size, colour or fabric?', 'faq.a3': 'Yes. We adapt dimensions and ergonomics and select shades of wood, fabrics and finishes for indoor and outdoor use.',
    'faq.q4': 'Will the furniture handle Bali’s climate and outdoor use?', 'faq.a4': 'The furniture is designed for the tropical climate: materials and structures are built for high humidity and temperature changes, and outdoor pieces use sun-resistant materials.',
    'faq.q5': 'What should I send for a quote?', 'faq.a5': 'The chosen models and quantities, a floor plan or references. A short description of the task also works: we will pick the models.',
    'faq.q6': 'Do you deliver and install on site?', 'faq.a6': 'Yes, we organise delivery and installation on site. It is the last step of the order after production.',
    'faq.q7': 'Do you work with designers and developers?', 'faq.a7': 'Yes. We offer ready solutions for designers, architects and developers and support the project from development to completion.',

    'lead.h2': 'Let’s create furniture for your project',
    'lead.lead': 'Contact us any way you like: we will find a solution, calculate the cost and prepare an offer',
    'lead.email': 'Email', 'lead.ig': 'Instagram', 'lead.group': 'Group', 'lead.group.v': '<i class="u5">UNIT.</i>DEVELOPER, Bali',
    'f.name': 'Name', 'f.contact': 'Phone, WhatsApp or email', 'f.contact.hint': 'For example, +62 812 000 00 00 or name@mail.com',
    'f.type': 'Property', 'f.type.ph': 'Choose the property type',
    'f.type.villa': 'Villa', 'f.type.house': 'House', 'f.type.apart': 'Apartment', 'f.type.hotel': 'Hotel', 'f.type.rest': 'Restaurant or café', 'f.type.other': 'Other',
    'f.type.garden': 'Terrace or garden', 'f.type.design': 'Design project',
    'f.need': 'What to furnish', 'f.need.lobby': 'Reception and lobby', 'f.need.rest': 'Restaurant or bar',
    'f.files': 'Photos, floor plan or references', 'f.files.btn': 'Attach files', 'f.files.hint': 'JPG, PNG, PDF or DWG, up to 10 files of 20 MB each',
    'f.files.rm': 'Remove file {name}', 'f.err.files': 'Not added: {list}. Files must be under 20 MB, up to 10 in total.',
    'ok.files': 'Files: {n}',
    'f.models': 'Models from the cart', 'f.models.empty': 'Nothing yet. Add models from the <a href="catalog.html">catalog</a> or describe the task below.',
    'f.models.edit': 'Change quantities',
    'f.msg': 'Comment', 'f.msg.ph': 'What you need, how many, by what date',
    'f.opt': 'optional',
    'f.agree': 'I agree to the <a href="consent.html">processing of personal data</a>',
    'f.submit': 'Send the request', 'f.sending': 'Sending…',
    'f.note': 'There are no prices on the site: we quote by model, quantity and fabric.',
    'f.err.title': 'Please check the form:',
    'f.err.name': 'Enter your name so we know how to address you.',
    'f.err.contact': 'Enter a phone, WhatsApp or email: at least 6 digits or an address with @.',
    'f.err.agree': 'Tick the consent to data processing, we cannot reply without it.',
    'ok.h': 'Request received',
    'ok.p': 'We will contact you at {c}, clarify the details and send a quote.',
    'ok.list': 'In the request:', 'ok.none': 'No models chosen, we will go by your comment.',
    'ok.more': 'Browse the catalog', 'ok.new': 'New request',

    'cart.h': 'Cart', 'cart.empty': 'Your cart is empty. Add models from the catalog, you can change quantities here.',
    'cart.go': 'Go to sending', 'cart.browse': 'Open the catalog',
    'cart.note': 'There are no prices on the site. We will send a quote for the models and quantities.',
    'cart.remove': 'Remove', 'cart.total': 'Models: {n}, pieces: {q}',
    'qty.minus': 'Fewer', 'qty.plus': 'More', 'qty': 'Quantity',
    'add': 'Add to cart', 'add.more': 'Add to cart', 'added': 'In cart',
    'toast.added': '{name} is in the cart', 'toast.open': 'Open cart',

    'cat.h1': 'Catalog',
    'cat.lead': 'Choose a model or send us a request: we will help you select furniture for your property',
    'cat.all': 'All', 'cat.filter': 'Category', 'cat.line': 'Line', 'cat.lineAll': 'All lines',
    'cat.shown': 'Models: {n}',
    'cat.empty.h': 'No ready models for these filters',
    'cat.empty.p': 'We can make it to order: describe the task in the request.',
    'cat.empty.reset': 'Reset filters', 'cat.empty.lead': 'Describe the task',
    'cat.noDims': 'Dimensions on request',
    'cat.env': 'Placement', 'env.indoor': 'Indoor', 'env.outdoor': 'Outdoor',
    'tag.fabric': 'Fabric options', 'tag.size': 'Custom size', 'card.price': 'Price on request',

    'pp.crumb': 'Catalog', 'pp.line': 'Line', 'pp.cat': 'Category', 'pp.dims': 'Dimensions, H × W × D',
    'pp.price': 'Price on request: we quote by quantity, fabric and size.',
    'pp.custom': 'Change size or fabric', 'pp.more': 'More from the {c} line', 'pp.similar': 'Similar models',
    'pp.photo': 'Photo {n} of {m}', 'pp.lineall': 'The whole {c} line in the catalog: {n}',
    'pp.custom.h': 'What can be changed',

    'cat.beds': 'Beds', 'cat.sofas': 'Sofas', 'cat.chairs': 'Chairs', 'cat.armchairs': 'Armchairs and poufs',
    'cat.nightstands': 'Nightstands', 'cat.outdoor': 'Outdoor sofas', 'cat.sunbeds': 'Sun loungers', 'cat.textile': 'Pillows',
    'n.models': '{n} model{e}',
    'd.chairs': 'A chair on a teak frame for a dining room, kitchen or bar. Fabric and size are adapted to the property.',
    'd.beds': 'A bed with an 18 mm plywood frame. Size, headboard and upholstery are adapted to a villa, home or hotel bedroom.',
    'd.armchairs': 'An armchair or pouf for the living room and bedroom. Fabric, colour and size are chosen for the interior.',
    'd.sofas': 'A sofa for a living room, reception or lounge. Fabric, size and configuration are chosen for the space.',
    'd.nightstands': 'A cube bedside table. The finish is chosen for the bedroom.',
    'd.outdoor': 'An outdoor sofa on a teak frame for a terrace or pool area. Materials are made for sun and humidity.',
    'd.sunbeds': 'A sun lounger on a teak frame for a terrace or pool. Materials are made for sun and humidity.',
    'd.textile': 'Decorative pillows for the collection’s sofas, in two colour options.',

    'ft.about': 'Designer furniture made in our own workshop in Bali for private and commercial properties.',
    'ft.nav': 'Sections', 'ft.contacts': 'Contacts', 'ft.legal': 'Legal information', 'ft.consent': 'Consent to data processing',
    'ft.part': 'Part of the <a href="https://unitdeveloper.com/" target="_blank" rel="noopener"><i class="u5">UNIT.</i>DEVELOPER</a> group',
    'ft.top': 'Back to top',
    'pdf.dl': 'Download the PDF catalog', 'pdf.ft': 'Catalog 2026 (PDF)', 'pdf.href': 'assets/UNIT-FURNITURE-catalog-2026-EN.pdf'
  }
};

/* перевод характеристик из data.js (значения там по-русски) */
window.SPEC_TR = {
  keys: { 'Изголовье': 'Headboard', 'Каркас': 'Frame', 'Цвет': 'Colour', 'Ножки': 'Legs', 'Варианты': 'Options' },
  keysRu: {},
  values: {
    'HMR 18 мм, орех': 'HMR 18 mm, walnut', 'Фанера 18 мм': '18 mm plywood', 'Серый': 'Grey', 'Металл': 'Metal',
    'Светлый': 'Light', 'Графитовый': 'Graphite', 'Коричневый': 'Brown', 'Тиковое дерево': 'Teak wood', 'Синий': 'Blue',
    'Тёмно-серый': 'Dark grey', 'Металл (Китай)': 'Metal (China)', 'Чёрно-белый': 'Black and white', 'Зеркальный': 'Mirrored',
    'A — оранжевый, B — тёмный': 'A: orange, B: dark', 'A — серый меланж, B — графит': 'A: grey melange, B: graphite',
    'A — синий, B — серый': 'A: blue, B: grey'
  }
};
