/* UNIT.FURNITURE: тексты RU/EN.
   Источник фактов: Figma «Каталог» 2026 (refs/catalog-2026-10/catalog-db.json).
   Цифр, которых нет в каталоге (сроки, гарантия, цены), не писать.
   <i class="u5">UNIT.</i> — связка бренда: UNIT. 500, хвост 400. Тире в копирайте не ставим. */
window.DICT = {
  ru: {
    'meta.title': 'UNIT.FURNITURE: авторская мебель собственного производства на Бали',
    'skip': 'К содержанию',
    'nav.collections': 'Коллекции', 'nav.catalog': 'Каталог', 'nav.production': 'Производство',
    'nav.custom': 'Кастомизация', 'nav.how': 'Как заказать', 'nav.faq': 'Вопросы',
    'nav.solutions': 'Решения', 'nav.projects': 'Проекты', 'nav.contacts': 'Контакты', 'nav.materials': 'Материалы',
    'hdr.cta': 'Получить расчёт', 'cta.quote': 'Получить расчёт', 'cart.back': 'К моделям', 'cart.closeBtn': 'Закрыть', 'cart.sum': 'Моделей: {n}, штук: {q}', 'cart.sum0': 'Модели не выбраны, опишите задачу в комментарии.', 'col.remove': 'Убрать линейку', 'hdr.menu': 'Меню', 'hdr.close': 'Закрыть меню', 'hdr.cart': 'Корзина',

    'hero.chip': 'Собственное производство', 'hero.tag2': 'Кастомизация', 'hero.tag3': 'Для дома, улицы и бизнеса',
    'hero.h1': 'Авторская мебель и интерьеры на Бали',
    'hero.lead': 'Коллекция 2026 и мебель под размеры вашего объекта. Стоимость по запросу',
    'hero.cta1': 'Смотреть каталог', 'hero.cta2': 'Обставить объект',
    'hero.cap': 'Sofa Outdoor Type 4, коллекция 2026',
    'path.h2': 'Мебель для дома и для объекта',
    'path.home': 'Для дома', 'path.home.t': 'Вилла, дом или апартаменты. Выберите модели в каталоге, укажите количество, и мы пришлём расчёт.', 'path.home.go': 'Выбрать модели',
    'path.pro': 'Для объекта', 'path.pro.t': 'Дизайнерам, архитекторам, застройщикам, отелям и ресторанам. Адаптируем модели и комплектуем объект целиком.', 'path.pro.go': 'Адаптировать под объект',

    'col.h2': 'Три линейки одной коллекции',
    'col.lead': 'Awan, Axis и Reason собраны в общем стиле: модели одной линейки легко комплектовать в один интерьер',
    'col.models': 'Модели', 'col.cats': 'Категории', 'col.frame': 'Материалы каркаса', 'col.count': 'Моделей в линейке',
    'col.go': 'Смотреть линейку', 'col.addall': 'Добавить линейку в корзину', 'col.added': 'Линейка в корзине',

    'cats.h2': 'Каталог по категориям',
    'cats.lead': '28 моделей коллекции 2026. Стоимость считаем под количество, ткань и размер',
    'cats.all': 'Весь каталог',

    'band.h': 'Собственное производство на Бали',
    'band.p': 'От выбора материалов до финальной сборки',

    'prod.h2': 'Делаем сами и проверяем на своих объектах',
    'prod.lead': '<i class="u5">UNIT.</i>FURNITURE входит в группу <i class="u5">UNIT.</i>, которая строит виллы и управляет ими на Бали',
    'prod.r1': 'Производство', 'prod.t1': 'Собственное производство на Бали позволяет контролировать каждый этап создания мебели: от выбора материалов до финальной сборки. Современное оборудование и контроль на каждом этапе дают точность исполнения.',
    'prod.r2': 'Дизайн', 'prod.t2': 'Хороший дизайн остаётся актуальным вне времени. Мы делаем мебель, в которой эстетика сочетается с комфортом, функциональностью и долговечностью.',
    'prod.r3': 'Проекты <i class="u5">UNIT.</i>', 'prod.t3': 'Мебель <i class="u5">UNIT.</i>FURNITURE стоит в собственных проектах <i class="u5">UNIT.</i>, поэтому мы уверены в её качестве, комфорте и долговечности.',

    'mat.h2': 'Материалы, рассчитанные на жизнь на Бали',
    'mat.lead': 'Подбираем материалы под назначение мебели: для комфорта, эстетики и долговечности',
    'mat.wood': 'Дерево', 'mat.wood.t': 'Натуральная древесина, подобранная под особенности каждой модели.',
    'mat.fabric': 'Ткани', 'mat.fabric.t': 'Разные фактуры, оттенки и уровни износостойкости для жилых и коммерческих пространств.',
    'mat.filling': 'Наполнение', 'mat.filling.t': 'Современные наполнители, которые сохраняют комфорт, форму и внешний вид мебели.',
    'mat.hardware': 'Фурнитура', 'mat.hardware.t': 'Надёжная и долговечная фурнитура и конструктивные решения для стабильной эксплуатации.',
    'clim.h3': 'Влажность и эксплуатация',
    'clim.1': 'Влажный климат', 'clim.1.t': 'Материалы и конструкции адаптированы к высокой влажности и перепадам температуры.',
    'clim.2': 'Солнце и улица', 'clim.2.t': 'Для открытых пространств используем материалы, устойчивые к солнцу.',
    'clim.3': 'Каждый день', 'clim.3.t': 'Мебель сохраняет внешний вид и комфорт даже при интенсивном использовании.',
    'clim.tag1': 'Для дома', 'clim.tag2': 'Для улицы и бассейна', 'clim.tag3': 'Для отелей и ресторанов',

    'cus.h2': 'Под ваш объект',
    'cus.lead': 'Адаптируем готовые модели или комплектуем виллу, дом, отель и ресторан целиком',
    'cus.r1': 'Размеры', 'cus.t1': 'Адаптируем размеры и эргономику под ваш объект.',
    'cus.r2': 'Цвета', 'cus.t2': 'Подбираем оттенки дерева, тканей и отделки.',
    'cus.r3': 'Ткани', 'cus.t3': 'Подбираем ткани и фактуры для помещений и улицы.',
    'cus.r4': 'Комплектация', 'cus.t4': 'От отдельных моделей до полной комплектации объекта.',
    'cus.cta': 'Обсудить объект',
    'sol.h3': 'Готовые решения для дизайнеров, архитекторов и застройщиков',
    'sol.bedroom': 'Спальня', 'sol.bedroom.t': 'Кровати, тумбы, кресла, пуфы, подушки',
    'sol.living': 'Гостиная', 'sol.living.t': 'Диваны, кресла, пуфы и подушки',
    'sol.outdoor': 'Терраса и бассейн', 'sol.outdoor.t': 'Уличные диваны, шезлонги и подушки',
    'sol.turnkey': 'Объект под ключ', 'sol.turnkey.t': 'Вилла, дом, отель или ресторан в едином стиле',
    'sol.go': 'Смотреть модели', 'sol.go.turnkey': 'Обсудить комплектацию',

    'proj.h2': 'Мебель в проектах <i class="u5">UNIT.</i>',
    'proj.lead': 'Наша мебель стоит в UNIT Space City и Black Sands Oasis. Откройте фото, чтобы увидеть модели в кадре',
    'proj.more': 'Показать все фото', 'proj.less': 'Свернуть фото',
    'proj.inshot': 'В этом кадре', 'proj.addshot': 'Добавить в корзину', 'proj.addshot2': 'Добавить модели в корзину', 'proj.inreq': 'Модели в корзине, открыть',
    'proj.open': 'Открыть фото', 'proj.close': 'Закрыть', 'proj.prev': 'Предыдущее фото', 'proj.next': 'Следующее фото',

    'how.h2': 'Как заказать мебель',
    'how.lead': 'От первого запроса до готовой мебели на объекте',
    'how.s1': 'Консультация', 'how.s1.t': 'Получаем ваш запрос с выбранными моделями, планом объекта или референсами.',
    'how.s2': 'Подбор', 'how.s2.t': 'Подбираем мебель, материалы и решения под ваш проект.',
    'how.s3': 'Расчёт', 'how.s3.t': 'Считаем стоимость заказа и называем срок.',
    'how.s4': 'Производство', 'how.s4.t': 'После согласования запускаем заказ в производство на Бали.',
    'how.s5': 'Доставка', 'how.s5.t': 'Организуем доставку и монтаж на объекте.',
    'how.cta': 'Оставить заявку',

    'faq.h2': 'Частые вопросы',
    'faq.lead': 'Коротко о том, что спрашивают перед заказом',
    'faq.q1': 'Почему на сайте нет цен?', 'faq.a1': 'Стоимость зависит от модели, размеров, ткани и количества. Добавьте модели в корзину с количеством, и мы пришлём расчёт под ваш объект.',
    'faq.q2': 'Какие сроки изготовления?', 'faq.a2': 'Срок называем вместе с расчётом: он зависит от моделей, количества и доработок. Если у объекта есть дата открытия или заселения, укажите её в заявке.',
    'faq.q3': 'Можно изменить размер, цвет или ткань?', 'faq.a3': 'Да. Адаптируем размеры и эргономику, подбираем оттенки дерева, тканей и отделки для помещений и улицы.',
    'faq.q4': 'Выдержит ли мебель климат Бали и улицу?', 'faq.a4': 'Мебель разрабатываем под тропический климат: материалы и конструкции рассчитаны на высокую влажность и перепады температуры, для улицы берём материалы, устойчивые к солнцу.',
    'faq.q5': 'Что прислать для расчёта?', 'faq.a5': 'Выбранные модели и количество, план объекта или референсы. Подойдёт и короткое описание задачи: подберём модели сами.',
    'faq.q6': 'Доставляете и собираете на объекте?', 'faq.a6': 'Да, организуем доставку и монтаж на объекте. Это последний шаг заказа после производства.',
    'faq.q7': 'Работаете с дизайнерами и застройщиками?', 'faq.a7': 'Да. Предлагаем готовые решения для дизайнеров, архитекторов и застройщиков и сопровождаем проект от разработки до реализации.',

    'lead.h2': 'Подберём мебель для вашего объекта',
    'lead.lead': 'Отправьте модели из корзины или опишите задачу. Ответим и пришлём расчёт',
    'lead.email': 'Почта', 'lead.ig': 'Instagram', 'lead.group': 'Группа компаний', 'lead.group.v': '<i class="u5">UNIT.</i>DEVELOPER, Бали',
    'f.name': 'Имя', 'f.contact': 'Телефон, WhatsApp или email', 'f.contact.hint': 'Например, +62 812 000 00 00 или name@mail.com',
    'f.type': 'Объект', 'f.type.ph': 'Выберите тип объекта',
    'f.type.villa': 'Вилла', 'f.type.house': 'Дом', 'f.type.apart': 'Апартаменты', 'f.type.hotel': 'Отель', 'f.type.rest': 'Ресторан или кафе', 'f.type.other': 'Другое',
    'f.type.garden': 'Терраса или сад', 'f.type.design': 'Дизайнерский проект',
    'f.need': 'Что подобрать', 'f.need.lobby': 'Ресепшн и лобби', 'f.need.rest': 'Ресторан или бар',
    'f.files': 'Фото, план или референсы', 'f.files.btn': 'Прикрепить файлы', 'f.files.hint': 'JPG, PNG, PDF или DWG, до 10 файлов по 20 МБ',
    'f.files.rm': 'Убрать файл {name}', 'f.err.files': 'Не добавили: {list}. Нужны файлы до 20 МБ, всего не больше 10.',
    'ok.files': 'Файлов: {n}',
    'f.models': 'Модели из корзины', 'f.models.empty': 'Пока пусто. Добавьте модели из <a href="catalog.html">каталога</a> или опишите задачу ниже.',
    'f.models.edit': 'Изменить количество',
    'f.msg': 'Комментарий', 'f.msg.ph': 'Что нужно, сколько, к какой дате',
    'f.opt': 'необязательно',
    'f.agree': 'Согласен на <a href="consent.html">обработку персональных данных</a>',
    'f.submit': 'Отправить заявку', 'f.sending': 'Отправляем…',
    'f.note': 'Цен на сайте нет: стоимость считаем под модели, количество и ткань.',
    'f.err.title': 'Проверьте форму:',
    'f.err.name': 'Укажите имя, чтобы мы знали, как к вам обращаться.',
    'f.err.contact': 'Укажите телефон, WhatsApp или email: минимум 6 цифр или адрес с @.',
    'f.err.agree': 'Отметьте согласие на обработку данных, без него мы не можем ответить.',
    'ok.h': 'Заявка принята',
    'ok.p': 'Свяжемся с вами по контакту {c}, уточним детали и пришлём расчёт.',
    'ok.list': 'В заявке:', 'ok.none': 'Модели не выбраны, ориентируемся на комментарий.',
    'ok.more': 'Смотреть каталог', 'ok.new': 'Новая заявка',

    'cart.h': 'Корзина', 'cart.empty': 'В корзине пока пусто. Добавьте модели из каталога, количество можно изменить здесь.',
    'cart.go': 'Перейти к отправке', 'cart.browse': 'Открыть каталог',
    'cart.note': 'Цен на сайте нет. Пришлём расчёт под модели и количество.',
    'cart.remove': 'Убрать', 'cart.total': 'Моделей: {n}, штук: {q}',
    'qty.minus': 'Меньше', 'qty.plus': 'Больше', 'qty': 'Количество',
    'add': 'В корзину', 'add.more': 'Добавить в корзину', 'added': 'В корзине',
    'toast.added': '{name} в корзине', 'toast.open': 'Открыть корзину',

    'cat.h1': 'Каталог',
    'cat.lead': '28 моделей коллекции 2026. Добавьте нужные в корзину и укажите количество',
    'cat.all': 'Все', 'cat.filter': 'Категория', 'cat.line': 'Линейка', 'cat.lineAll': 'Все линейки',
    'cat.shown': 'Моделей: {n}',
    'cat.empty.h': 'Под эти фильтры готовых моделей нет',
    'cat.empty.p': 'Сделаем под заказ: опишите задачу в заявке.',
    'cat.empty.reset': 'Сбросить фильтры', 'cat.empty.lead': 'Описать задачу',
    'cat.noDims': 'Размеры по запросу',
    'cat.env': 'Где стоит', 'env.indoor': 'Для помещений', 'env.outdoor': 'Для улицы',
    'tag.fabric': 'Ткань на выбор', 'tag.size': 'Размер под заказ', 'card.price': 'Стоимость по запросу',

    'pp.crumb': 'Каталог', 'pp.line': 'Линейка', 'pp.cat': 'Категория', 'pp.dims': 'Размеры, В × Ш × Г',
    'pp.price': 'Стоимость по запросу: считаем под количество, ткань и размер.',
    'pp.custom': 'Изменить размер или ткань', 'pp.more': 'Ещё из линейки {c}', 'pp.similar': 'Похожие модели',
    'pp.photo': 'Фото {n} из {m}', 'pp.lineall': 'Вся линейка {c} в каталоге: {n}',
    'pp.custom.h': 'Что можно изменить',

    'cat.beds': 'Кровати', 'cat.sofas': 'Диваны', 'cat.chairs': 'Стулья', 'cat.armchairs': 'Кресла и пуфы',
    'cat.nightstands': 'Тумбы', 'cat.outdoor': 'Уличные диваны', 'cat.sunbeds': 'Шезлонги', 'cat.textile': 'Подушки',
    'n.models': '{n} модел{e}',
    'd.chairs': 'Стул на тиковом каркасе для столовой, кухни или бара. Ткань и размеры адаптируем под объект.',
    'd.beds': 'Кровать с каркасом из фанеры 18 мм. Размер, изголовье и обивку адаптируем под спальню виллы, дома или отельного номера.',
    'd.armchairs': 'Кресло или пуф для гостиной и спальни. Ткань, цвет и размеры подбираем под интерьер.',
    'd.sofas': 'Диван для гостиной, ресепшн или лаунж-зоны. Ткань, размер и конфигурацию подбираем под пространство.',
    'd.nightstands': 'Прикроватная тумба-куб. Отделку подбираем под спальню.',
    'd.outdoor': 'Уличный диван на тиковом каркасе для террасы и зоны у бассейна. Материалы рассчитаны на солнце и влажность.',
    'd.sunbeds': 'Шезлонг на тиковом каркасе для террасы и бассейна. Материалы рассчитаны на солнце и влажность.',
    'd.textile': 'Декоративные подушки к диванам коллекции, в двух вариантах цвета.',

    'ft.about': 'Авторская мебель собственного производства на Бали для частных и коммерческих объектов.',
    'ft.nav': 'Разделы', 'ft.contacts': 'Контакты', 'ft.legal': 'Правовая информация', 'ft.consent': 'Согласие на обработку данных',
    'ft.part': 'Часть группы <a href="https://unitdeveloper.com/" target="_blank" rel="noopener"><i class="u5">UNIT.</i>DEVELOPER</a>',
    'ft.top': 'Наверх',
    'pdf.dl': 'Скачать каталог PDF', 'pdf.ft': 'Каталог 2026 (PDF)', 'pdf.href': 'assets/UNIT-FURNITURE-catalog-2026-RU.pdf'
  },
  en: {
    'meta.title': 'UNIT.FURNITURE: designer furniture made in our own workshop in Bali',
    'skip': 'Skip to content',
    'nav.collections': 'Collections', 'nav.catalog': 'Catalog', 'nav.production': 'Production',
    'nav.custom': 'Customisation', 'nav.how': 'How to order', 'nav.faq': 'FAQ',
    'nav.solutions': 'Solutions', 'nav.projects': 'Projects', 'nav.contacts': 'Contacts', 'nav.materials': 'Materials',
    'hdr.cta': 'Get a quote', 'cta.quote': 'Get a quote', 'cart.back': 'Back to models', 'cart.closeBtn': 'Close', 'cart.sum': 'Models: {n}, pieces: {q}', 'cart.sum0': 'No models chosen, describe the task in the comment.', 'col.remove': 'Remove the line', 'hdr.menu': 'Menu', 'hdr.close': 'Close menu', 'hdr.cart': 'Cart',

    'hero.chip': 'Our own workshop', 'hero.tag2': 'Customisation', 'hero.tag3': 'Indoor, outdoor, commercial',
    'hero.h1': 'Designer furniture and interiors in Bali',
    'hero.lead': 'The 2026 collection and furniture made to fit your property. Price on request',
    'hero.cta1': 'Browse the catalog', 'hero.cta2': 'Furnish a property',
    'hero.cap': 'Sofa Outdoor Type 4, 2026 collection',
    'path.h2': 'Furniture for a home and for a property',
    'path.home': 'For a home', 'path.home.t': 'A villa, house or apartment. Choose models in the catalog, set quantities and we will send a quote.', 'path.home.go': 'Choose models',
    'path.pro': 'For a property', 'path.pro.t': 'For designers, architects, developers, hotels and restaurants. We adapt models and furnish the whole property.', 'path.pro.go': 'Adapt to your property',

    'col.h2': 'Three lines, one collection',
    'col.lead': 'Awan, Axis and Reason share one style, so models from a line furnish a single interior with ease',
    'col.models': 'Models', 'col.cats': 'Categories', 'col.frame': 'Frame materials', 'col.count': 'Models in the line',
    'col.go': 'View the line', 'col.addall': 'Add the line to the cart', 'col.added': 'Line is in the cart',

    'cats.h2': 'Catalog by category',
    'cats.lead': '28 models of the 2026 collection. We quote by quantity, fabric and size',
    'cats.all': 'Full catalog',

    'band.h': 'Our own workshop in Bali',
    'band.p': 'From material selection to final assembly',

    'prod.h2': 'We make it ourselves and test it in our own properties',
    'prod.lead': '<i class="u5">UNIT.</i>FURNITURE is part of the <i class="u5">UNIT.</i> group, which builds and manages villas in Bali',
    'prod.r1': 'Production', 'prod.t1': 'In-house production in Bali lets us control every stage, from material selection to final assembly. Modern equipment and checks at every step keep the execution precise.',
    'prod.r2': 'Design', 'prod.t2': 'Good design stays relevant beyond trends. We make furniture where aesthetics meet comfort, function and durability.',
    'prod.r3': '<i class="u5">UNIT.</i> projects', 'prod.t3': '<i class="u5">UNIT.</i>FURNITURE is used in <i class="u5">UNIT.</i>’s own projects, which is why we are confident in its quality, comfort and durability.',

    'mat.h2': 'Materials made for life in Bali',
    'mat.lead': 'We choose materials for the purpose of each piece: comfort, aesthetics and durability',
    'mat.wood': 'Wood', 'mat.wood.t': 'Natural wood selected for the features of each model.',
    'mat.fabric': 'Fabrics', 'mat.fabric.t': 'Textures, shades and wear resistance for residential and commercial spaces.',
    'mat.filling': 'Filling', 'mat.filling.t': 'Modern fillings that keep the comfort, shape and look of the furniture.',
    'mat.hardware': 'Hardware', 'mat.hardware.t': 'Reliable, durable hardware and structural solutions for stable everyday use.',
    'clim.h3': 'Humidity and everyday use',
    'clim.1': 'Humid climate', 'clim.1.t': 'Materials and structures are adapted to high humidity and temperature changes.',
    'clim.2': 'Sun and outdoors', 'clim.2.t': 'For open spaces we use materials resistant to the sun.',
    'clim.3': 'Every day', 'clim.3.t': 'The furniture keeps its look and comfort even with intensive use.',
    'clim.tag1': 'For homes', 'clim.tag2': 'For outdoor and pool areas', 'clim.tag3': 'For hotels and restaurants',

    'cus.h2': 'Made for your property',
    'cus.lead': 'We adapt ready models or furnish a whole villa, house, hotel or restaurant',
    'cus.r1': 'Dimensions', 'cus.t1': 'We adapt dimensions and ergonomics to your property.',
    'cus.r2': 'Colours', 'cus.t2': 'We select shades of wood, fabrics and finishes.',
    'cus.r3': 'Fabrics', 'cus.t3': 'We select fabrics and textures for indoor and outdoor spaces.',
    'cus.r4': 'Furnishing', 'cus.t4': 'From single models to furnishing the entire property.',
    'cus.cta': 'Discuss your property',
    'sol.h3': 'Ready solutions for designers, architects and developers',
    'sol.bedroom': 'Bedroom', 'sol.bedroom.t': 'Beds, nightstands, armchairs, poufs, pillows',
    'sol.living': 'Living room', 'sol.living.t': 'Sofas, armchairs, poufs and pillows',
    'sol.outdoor': 'Terrace and pool', 'sol.outdoor.t': 'Outdoor sofas, sun loungers and pillows',
    'sol.turnkey': 'Turnkey property', 'sol.turnkey.t': 'A villa, house, hotel or restaurant in one style',
    'sol.go': 'View models', 'sol.go.turnkey': 'Discuss furnishing',

    'proj.h2': 'Furniture in <i class="u5">UNIT.</i> projects',
    'proj.lead': 'Our furniture is in UNIT Space City and Black Sands Oasis. Open a photo to see the models in the shot',
    'proj.more': 'Show all photos', 'proj.less': 'Hide photos',
    'proj.inshot': 'In this shot', 'proj.addshot': 'Add to cart', 'proj.addshot2': 'Add these to cart', 'proj.inreq': 'In the cart, open it',
    'proj.open': 'Open photo', 'proj.close': 'Close', 'proj.prev': 'Previous photo', 'proj.next': 'Next photo',

    'how.h2': 'How to order furniture',
    'how.lead': 'From the first request to finished furniture on site',
    'how.s1': 'Consultation', 'how.s1.t': 'We receive your request with chosen models, a floor plan or references.',
    'how.s2': 'Selection', 'how.s2.t': 'We select furniture, materials and solutions for your project.',
    'how.s3': 'Quote', 'how.s3.t': 'We calculate the cost of the order and give the lead time.',
    'how.s4': 'Production', 'how.s4.t': 'Once approved, the order goes into production in Bali.',
    'how.s5': 'Delivery', 'how.s5.t': 'We organise delivery and installation on site.',
    'how.cta': 'Send a request',

    'faq.h2': 'Frequently asked questions',
    'faq.lead': 'Short answers to what people ask before ordering',
    'faq.q1': 'Why are there no prices on the site?', 'faq.a1': 'The cost depends on the model, size, fabric and quantity. Add models to the cart with quantities and we will send a quote for your property.',
    'faq.q2': 'How long does production take?', 'faq.a2': 'We give the lead time together with the quote: it depends on the models, quantity and changes. If your property has an opening or move-in date, put it in the request.',
    'faq.q3': 'Can I change the size, colour or fabric?', 'faq.a3': 'Yes. We adapt dimensions and ergonomics and select shades of wood, fabrics and finishes for indoor and outdoor use.',
    'faq.q4': 'Will the furniture handle Bali’s climate and outdoor use?', 'faq.a4': 'The furniture is designed for the tropical climate: materials and structures are built for high humidity and temperature changes, and outdoor pieces use sun-resistant materials.',
    'faq.q5': 'What should I send for a quote?', 'faq.a5': 'The chosen models and quantities, a floor plan or references. A short description of the task also works: we will pick the models.',
    'faq.q6': 'Do you deliver and install on site?', 'faq.a6': 'Yes, we organise delivery and installation on site. It is the last step of the order after production.',
    'faq.q7': 'Do you work with designers and developers?', 'faq.a7': 'Yes. We offer ready solutions for designers, architects and developers and support the project from development to completion.',

    'lead.h2': 'We will select furniture for your property',
    'lead.lead': 'Send the models from your cart or describe the task. We will reply with a quote',
    'lead.email': 'Email', 'lead.ig': 'Instagram', 'lead.group': 'Group', 'lead.group.v': '<i class="u5">UNIT.</i>DEVELOPER, Bali',
    'f.name': 'Name', 'f.contact': 'Phone, WhatsApp or email', 'f.contact.hint': 'For example, +62 812 000 00 00 or name@mail.com',
    'f.type': 'Property', 'f.type.ph': 'Choose the property type',
    'f.type.villa': 'Villa', 'f.type.house': 'House', 'f.type.apart': 'Apartment', 'f.type.hotel': 'Hotel', 'f.type.rest': 'Restaurant or café', 'f.type.other': 'Other',
    'f.type.garden': 'Terrace or garden', 'f.type.design': 'Design project',
    'f.need': 'What to furnish', 'f.need.lobby': 'Reception and lobby', 'f.need.rest': 'Restaurant or bar',
    'f.files': 'Photos, floor plan or references', 'f.files.btn': 'Attach files', 'f.files.hint': 'JPG, PNG, PDF or DWG, up to 10 files of 20 MB each',
    'f.files.rm': 'Remove file {name}', 'f.err.files': 'Not added: {list}. Files must be under 20 MB, up to 10 in total.',
    'ok.files': 'Files: {n}',
    'f.models': 'Models from the cart', 'f.models.empty': 'Nothing yet. Add models from the <a href="catalog.html">catalog</a> or describe the task below.',
    'f.models.edit': 'Change quantities',
    'f.msg': 'Comment', 'f.msg.ph': 'What you need, how many, by what date',
    'f.opt': 'optional',
    'f.agree': 'I agree to the <a href="consent.html">processing of personal data</a>',
    'f.submit': 'Send the request', 'f.sending': 'Sending…',
    'f.note': 'There are no prices on the site: we quote by model, quantity and fabric.',
    'f.err.title': 'Please check the form:',
    'f.err.name': 'Enter your name so we know how to address you.',
    'f.err.contact': 'Enter a phone, WhatsApp or email: at least 6 digits or an address with @.',
    'f.err.agree': 'Tick the consent to data processing, we cannot reply without it.',
    'ok.h': 'Request received',
    'ok.p': 'We will contact you at {c}, clarify the details and send a quote.',
    'ok.list': 'In the request:', 'ok.none': 'No models chosen, we will go by your comment.',
    'ok.more': 'Browse the catalog', 'ok.new': 'New request',

    'cart.h': 'Cart', 'cart.empty': 'Your cart is empty. Add models from the catalog, you can change quantities here.',
    'cart.go': 'Go to sending', 'cart.browse': 'Open the catalog',
    'cart.note': 'There are no prices on the site. We will send a quote for the models and quantities.',
    'cart.remove': 'Remove', 'cart.total': 'Models: {n}, pieces: {q}',
    'qty.minus': 'Fewer', 'qty.plus': 'More', 'qty': 'Quantity',
    'add': 'Add to cart', 'add.more': 'Add to cart', 'added': 'In cart',
    'toast.added': '{name} is in the cart', 'toast.open': 'Open cart',

    'cat.h1': 'Catalog',
    'cat.lead': '28 models of the 2026 collection. Add the ones you need and set quantities',
    'cat.all': 'All', 'cat.filter': 'Category', 'cat.line': 'Line', 'cat.lineAll': 'All lines',
    'cat.shown': 'Models: {n}',
    'cat.empty.h': 'No ready models for these filters',
    'cat.empty.p': 'We can make it to order: describe the task in the request.',
    'cat.empty.reset': 'Reset filters', 'cat.empty.lead': 'Describe the task',
    'cat.noDims': 'Dimensions on request',
    'cat.env': 'Placement', 'env.indoor': 'Indoor', 'env.outdoor': 'Outdoor',
    'tag.fabric': 'Fabric options', 'tag.size': 'Custom size', 'card.price': 'Price on request',

    'pp.crumb': 'Catalog', 'pp.line': 'Line', 'pp.cat': 'Category', 'pp.dims': 'Dimensions, H × W × D',
    'pp.price': 'Price on request: we quote by quantity, fabric and size.',
    'pp.custom': 'Change size or fabric', 'pp.more': 'More from the {c} line', 'pp.similar': 'Similar models',
    'pp.photo': 'Photo {n} of {m}', 'pp.lineall': 'The whole {c} line in the catalog: {n}',
    'pp.custom.h': 'What can be changed',

    'cat.beds': 'Beds', 'cat.sofas': 'Sofas', 'cat.chairs': 'Chairs', 'cat.armchairs': 'Armchairs and poufs',
    'cat.nightstands': 'Nightstands', 'cat.outdoor': 'Outdoor sofas', 'cat.sunbeds': 'Sun loungers', 'cat.textile': 'Pillows',
    'n.models': '{n} model{e}',
    'd.chairs': 'A chair on a teak frame for a dining room, kitchen or bar. Fabric and size are adapted to the property.',
    'd.beds': 'A bed with an 18 mm plywood frame. Size, headboard and upholstery are adapted to a villa, home or hotel bedroom.',
    'd.armchairs': 'An armchair or pouf for the living room and bedroom. Fabric, colour and size are chosen for the interior.',
    'd.sofas': 'A sofa for a living room, reception or lounge. Fabric, size and configuration are chosen for the space.',
    'd.nightstands': 'A cube bedside table. The finish is chosen for the bedroom.',
    'd.outdoor': 'An outdoor sofa on a teak frame for a terrace or pool area. Materials are made for sun and humidity.',
    'd.sunbeds': 'A sun lounger on a teak frame for a terrace or pool. Materials are made for sun and humidity.',
    'd.textile': 'Decorative pillows for the collection’s sofas, in two colour options.',

    'ft.about': 'Designer furniture made in our own workshop in Bali for private and commercial properties.',
    'ft.nav': 'Sections', 'ft.contacts': 'Contacts', 'ft.legal': 'Legal information', 'ft.consent': 'Consent to data processing',
    'ft.part': 'Part of the <a href="https://unitdeveloper.com/" target="_blank" rel="noopener"><i class="u5">UNIT.</i>DEVELOPER</a> group',
    'ft.top': 'Back to top',
    'pdf.dl': 'Download the PDF catalog', 'pdf.ft': 'Catalog 2026 (PDF)', 'pdf.href': 'assets/UNIT-FURNITURE-catalog-2026-EN.pdf'
  }
};

/* перевод характеристик из data.js (значения там по-русски) */
window.SPEC_TR = {
  keys: { 'Изголовье': 'Headboard', 'Каркас': 'Frame', 'Цвет': 'Colour', 'Ножки': 'Legs', 'Варианты': 'Options' },
  keysRu: {},
  values: {
    'HMR 18 мм, орех': 'HMR 18 mm, walnut', 'Фанера 18 мм': '18 mm plywood', 'Серый': 'Grey', 'Металл': 'Metal',
    'Светлый': 'Light', 'Графитовый': 'Graphite', 'Коричневый': 'Brown', 'Тиковое дерево': 'Teak wood', 'Синий': 'Blue',
    'Тёмно-серый': 'Dark grey', 'Металл (Китай)': 'Metal (China)', 'Чёрно-белый': 'Black and white', 'Зеркальный': 'Mirrored',
    'A — оранжевый, B — тёмный': 'A: orange, B: dark', 'A — серый меланж, B — графит': 'A: grey melange, B: graphite',
    'A — синий, B — серый': 'A: blue, B: grey'
  }
};
